name: Run Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: |
          npm test
          if [ $? -eq 0 ]; then
            echo '{"schemaVersion": 1, "label": "Tests", "message": "passing", "color": "green"}' > badge.json
          else
            echo '{"schemaVersion": 1, "label": "Tests", "message": "failing", "color": "red"}' > badge.json
          fi

      - name: Upload badge to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          destination_dir: badges
          keep_files: true
